# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'norkqeditor.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NorkkQEditor(object):
    def setupUi(self, NorkkQEditor):
        NorkkQEditor.setObjectName("NorkkQEditor")
        NorkkQEditor.resize(300, 540)
        NorkkQEditor.setMinimumSize(QtCore.QSize(300, 540))
        NorkkQEditor.setMaximumSize(QtCore.QSize(300, 540))
        self.centralwidget = QtWidgets.QWidget(NorkkQEditor)
        self.centralwidget.setObjectName("centralwidget")
        self.sekmeler = QtWidgets.QTabWidget(self.centralwidget)
        self.sekmeler.setGeometry(QtCore.QRect(10, 10, 280, 521))
        self.sekmeler.setObjectName("sekmeler")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.pin_basligi_entry = QtWidgets.QLineEdit(self.tab)
        self.pin_basligi_entry.setGeometry(QtCore.QRect(10, 30, 251, 20))
        self.pin_basligi_entry.setObjectName("pin_basligi_entry")
        self.pin_basligi_label = QtWidgets.QLabel(self.tab)
        self.pin_basligi_label.setGeometry(QtCore.QRect(10, 10, 241, 16))
        self.pin_basligi_label.setObjectName("pin_basligi_label")
        self.pin_aciklamasi_label = QtWidgets.QLabel(self.tab)
        self.pin_aciklamasi_label.setGeometry(QtCore.QRect(10, 60, 241, 16))
        self.pin_aciklamasi_label.setObjectName("pin_aciklamasi_label")
        self.pin_aciklamasi_entry = QtWidgets.QPlainTextEdit(self.tab)
        self.pin_aciklamasi_entry.setGeometry(QtCore.QRect(10, 80, 251, 61))
        self.pin_aciklamasi_entry.setObjectName("pin_aciklamasi_entry")
        self.pano_ismi_label = QtWidgets.QLabel(self.tab)
        self.pano_ismi_label.setGeometry(QtCore.QRect(10, 150, 241, 16))
        self.pano_ismi_label.setObjectName("pano_ismi_label")
        self.pano_ismi_entry = QtWidgets.QLineEdit(self.tab)
        self.pano_ismi_entry.setGeometry(QtCore.QRect(10, 170, 251, 20))
        self.pano_ismi_entry.setObjectName("pano_ismi_entry")
        self.goruntu_view = QtWidgets.QLabel(self.tab)
        self.goruntu_view.setGeometry(QtCore.QRect(10, 270, 251, 181))
        self.goruntu_view.setStyleSheet("border: 1px solid black;")
        self.goruntu_view.setText("")
        self.goruntu_view.setObjectName("goruntu_view")
        self.goruntu_view.setScaledContents(True)
        self.goruntu_label = QtWidgets.QLabel(self.tab)
        self.goruntu_label.setGeometry(QtCore.QRect(10, 250, 241, 16))
        self.goruntu_label.setObjectName("goruntu_label")
        self.goruntu_sec_buton = QtWidgets.QPushButton(self.tab)
        self.goruntu_sec_buton.setGeometry(QtCore.QRect(10, 460, 121, 23))
        self.goruntu_sec_buton.setDefault(False)
        self.goruntu_sec_buton.setFlat(False)
        self.goruntu_sec_buton.setObjectName("goruntu_sec_buton")
        self.pini_ekle_buton = QtWidgets.QPushButton(self.tab)
        self.pini_ekle_buton.setGeometry(QtCore.QRect(140, 460, 121, 23))
        self.pini_ekle_buton.setDefault(False)
        self.pini_ekle_buton.setFlat(False)
        self.pini_ekle_buton.setObjectName("pini_ekle_buton")
        self.pin_link_label = QtWidgets.QLabel(self.tab)
        self.pin_link_label.setGeometry(QtCore.QRect(10, 200, 241, 16))
        self.pin_link_label.setObjectName("pin_link_label")
        self.pin_link_entry = QtWidgets.QLineEdit(self.tab)
        self.pin_link_entry.setGeometry(QtCore.QRect(10, 220, 251, 20))
        self.pin_link_entry.setObjectName("pin_link_entry")
        self.sekmeler.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.baslik_anahtar_kelime_grup = QtWidgets.QGroupBox(self.tab_2)
        self.baslik_anahtar_kelime_grup.setGeometry(QtCore.QRect(10, 10, 251, 80))
        self.baslik_anahtar_kelime_grup.setObjectName("baslik_anahtar_kelime_grup")
        self.baslik_entry = QtWidgets.QLineEdit(self.baslik_anahtar_kelime_grup)
        self.baslik_entry.setGeometry(QtCore.QRect(10, 24, 231, 20))
        self.baslik_entry.setObjectName("baslik_entry")
        self.baslik_ekle_buton = QtWidgets.QPushButton(self.baslik_anahtar_kelime_grup)
        self.baslik_ekle_buton.setGeometry(QtCore.QRect(10, 50, 111, 23))
        self.baslik_ekle_buton.setObjectName("baslik_ekle_buton")
        self.baslik_sil_buton = QtWidgets.QPushButton(self.baslik_anahtar_kelime_grup)
        self.baslik_sil_buton.setGeometry(QtCore.QRect(130, 50, 111, 23))
        self.baslik_sil_buton.setObjectName("baslik_sil_buton")
        self.aciklama_grup = QtWidgets.QGroupBox(self.tab_2)
        self.aciklama_grup.setGeometry(QtCore.QRect(10, 100, 251, 80))
        self.aciklama_grup.setObjectName("aciklama_grup")
        self.aciklama_entry = QtWidgets.QLineEdit(self.aciklama_grup)
        self.aciklama_entry.setGeometry(QtCore.QRect(10, 24, 231, 20))
        self.aciklama_entry.setObjectName("aciklama_entry")
        self.aciklama_ekle_buton = QtWidgets.QPushButton(self.aciklama_grup)
        self.aciklama_ekle_buton.setGeometry(QtCore.QRect(10, 50, 111, 23))
        self.aciklama_ekle_buton.setObjectName("aciklama_ekle_buton")
        self.aciklama_sil_buton = QtWidgets.QPushButton(self.aciklama_grup)
        self.aciklama_sil_buton.setGeometry(QtCore.QRect(130, 50, 111, 23))
        self.aciklama_sil_buton.setObjectName("aciklama_sil_buton")
        self.link_grup = QtWidgets.QGroupBox(self.tab_2)
        self.link_grup.setGeometry(QtCore.QRect(10, 190, 251, 80))
        self.link_grup.setObjectName("link_grup")
        self.link_entry = QtWidgets.QLineEdit(self.link_grup)
        self.link_entry.setGeometry(QtCore.QRect(10, 24, 231, 20))
        self.link_entry.setObjectName("link_entry")
        self.link_ekle_buton = QtWidgets.QPushButton(self.link_grup)
        self.link_ekle_buton.setGeometry(QtCore.QRect(10, 50, 111, 23))
        self.link_ekle_buton.setObjectName("link_ekle_buton")
        self.link_sil_buton = QtWidgets.QPushButton(self.link_grup)
        self.link_sil_buton.setGeometry(QtCore.QRect(130, 50, 111, 23))
        self.link_sil_buton.setObjectName("link_sil_buton")
        self.pano_grup = QtWidgets.QGroupBox(self.tab_2)
        self.pano_grup.setGeometry(QtCore.QRect(10, 280, 251, 80))
        self.pano_grup.setObjectName("pano_grup")
        self.pano_entry = QtWidgets.QLineEdit(self.pano_grup)
        self.pano_entry.setGeometry(QtCore.QRect(10, 24, 231, 20))
        self.pano_entry.setObjectName("pano_entry")
        self.pano_ekle_buton = QtWidgets.QPushButton(self.pano_grup)
        self.pano_ekle_buton.setGeometry(QtCore.QRect(10, 50, 111, 23))
        self.pano_ekle_buton.setObjectName("pano_ekle_buton")
        self.pano_sil_buton = QtWidgets.QPushButton(self.pano_grup)
        self.pano_sil_buton.setGeometry(QtCore.QRect(130, 50, 111, 23))
        self.pano_sil_buton.setObjectName("pano_sil_buton")

        self.basliklar_sil = QtWidgets.QPushButton(self.tab_2)
        self.basliklar_sil.setGeometry(QtCore.QRect(20, 370, 111, 23))
        self.basliklar_sil.setObjectName("basliklar_sil_buton")

        self.aciklamalar_sil = QtWidgets.QPushButton(self.tab_2)
        self.aciklamalar_sil.setGeometry(QtCore.QRect(140, 370, 111, 23))
        self.aciklamalar_sil.setObjectName("aciklamalar_sil_buton")

        self.linkler_sil = QtWidgets.QPushButton(self.tab_2)
        self.linkler_sil.setGeometry(QtCore.QRect(20, 400, 111, 23))
        self.linkler_sil.setObjectName("linkler_sil_buton")

        self.resimler_sil = QtWidgets.QPushButton(self.tab_2)
        self.resimler_sil.setGeometry(QtCore.QRect(140, 400, 111, 23))
        self.resimler_sil.setObjectName("resimler_sil_buton")

        self.panolar_sil = QtWidgets.QPushButton(self.tab_2)
        self.panolar_sil.setGeometry(QtCore.QRect(20, 430, 111, 23))
        self.panolar_sil.setObjectName("panolar_sil_buton")


        self.sekmeler.addTab(self.tab_2, "")
        NorkkQEditor.setCentralWidget(self.centralwidget)

        self.retranslateUi(NorkkQEditor)
        self.sekmeler.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(NorkkQEditor)

    def retranslateUi(self, NorkkQEditor):
        _translate = QtCore.QCoreApplication.translate
        NorkkQEditor.setWindowTitle(_translate("NorkkQEditor", "NorkQ Editor"))
        NorkkQEditor.setWindowIcon(QtGui.QIcon('logo.ico'))
        self.pin_basligi_label.setText(_translate("NorkkQEditor", "Pin Başlığı"))
        self.pin_aciklamasi_label.setText(_translate("NorkkQEditor", "Pin Açıklaması"))
        self.pano_ismi_label.setText(_translate("NorkkQEditor", "Pano İsmi"))
        self.goruntu_label.setText(_translate("NorkkQEditor", "Görüntü"))
        self.goruntu_sec_buton.setText(_translate("NorkkQEditor", "Görüntü Seç"))
        self.pini_ekle_buton.setText(_translate("NorkkQEditor", "Pini Ekle"))
        self.pin_link_label.setText(_translate("NorkkQEditor", "Link"))
        self.sekmeler.setTabText(self.sekmeler.indexOf(self.tab), _translate("NorkkQEditor", "Pin Oluştur"))
        self.baslik_anahtar_kelime_grup.setTitle(_translate("NorkkQEditor", "Başlık Anahtar Kelime"))
        self.baslik_ekle_buton.setText(_translate("NorkkQEditor", "Ekle"))
        self.baslik_sil_buton.setText(_translate("NorkkQEditor", "Sil"))
        self.aciklama_grup.setTitle(_translate("NorkkQEditor", "Açıklama Anahtar Kelime"))
        self.aciklama_ekle_buton.setText(_translate("NorkkQEditor", "Ekle"))
        self.aciklama_sil_buton.setText(_translate("NorkkQEditor", "Sil"))
        self.link_grup.setTitle(_translate("NorkkQEditor", "Link"))
        self.link_ekle_buton.setText(_translate("NorkkQEditor", "Ekle"))
        self.link_sil_buton.setText(_translate("NorkkQEditor", "Sil"))
        self.pano_grup.setTitle(_translate("NorkkQEditor", "Pano"))
        self.pano_ekle_buton.setText(_translate("NorkkQEditor", "Ekle"))
        self.pano_sil_buton.setText(_translate("NorkkQEditor", "Sil"))
        self.basliklar_sil.setText(_translate("NorkQEditor", "Başlıkları Temizle"))
        self.aciklamalar_sil.setText(_translate("NorkQEditor", "Açıklamaları Temizle"))
        self.linkler_sil.setText(_translate("NorkQEditor", "Linkleri Temizle"))
        self.resimler_sil.setText(_translate("NorkQEditor", "Resimleri Temizle"))
        self.panolar_sil.setText(_translate("NorkQEditor", "Panoları Temizle"))
        self.sekmeler.setTabText(self.sekmeler.indexOf(self.tab_2), _translate("NorkkQEditor", "Anahtar Kelime Ekle / Sil"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    app.setStyle('Fusion')
    NorkkQEditor = QtWidgets.QMainWindow()
    ui = Ui_NorkkQEditor()
    ui.setupUi(NorkkQEditor)
    NorkkQEditor.show()
    sys.exit(app.exec_())
